#!/usr/bin/env node
const mock = require('mock-require')
const stackTrace = require('stack-trace');

const testList = []

const collectTestMock = type => function (testTitle, implementation) {
	const st = stackTrace.get();
	const title = typeof testTitle === 'string' ? testTitle : ''
	testList.push([title, st[1].getLineNumber(), type])
}
const avaMock = {
	test: collectTestMock('standard')
};
avaMock.test.cb = collectTestMock('standard');
avaMock.test.serial = collectTestMock('standard');
avaMock.test.only = collectTestMock('standard');
avaMock.test.skip = collectTestMock('skip');
avaMock.test.todo = collectTestMock('todo');
avaMock.test.failing = collectTestMock('failing');
avaMock.test.before = collectTestMock('before');
avaMock.test.beforeEach = collectTestMock('beforeEach');
avaMock.test.after = collectTestMock('after');
avaMock.test.afterEach = collectTestMock('afterEach');

mock('ava',avaMock);

require(process.argv[2]);
mock.stop('ava')
console.log(JSON.stringify(testList));
