#!/usr/bin/env node
const mock = require('mock-require')
const stackTrace = require('stack-trace');

const testList = []

const collectTestMock = type => function (testTitle, implementation) {
	const st = stackTrace.get();
	const title = typeof testTitle === 'string' ? testTitle : ''
	testList.push([title, st[1].getLineNumber(), type])
}
const test = collectTestMock('standard');
test.cb = collectTestMock('standard');
test.serial = collectTestMock('standard');
test.only = collectTestMock('standard');
test.skip = collectTestMock('skip');
test.todo = collectTestMock('todo');
test.failing = collectTestMock('failing');
test.before = collectTestMock('before');
test.beforeEach = collectTestMock('beforeEach');
test.after = collectTestMock('after');
test.afterEach = collectTestMock('afterEach');
test.test = test; // testinception

mock('ava', test);

require(process.argv[2]);
mock.stop('ava')
console.log(JSON.stringify(testList));
