#!/bin/bash
mkdir -p /tmp/vscode-ava
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cdir="$(pwd)"
cd $dir
cat - | tee /tmp/vscode-ava/tests-$1-exec.tap | ./node_modules/.bin/tap-summary
cd $cdir